// 🔥 Force mapping MobileNet predictions -> Project Ingredients (recipes.js)
const forceMap = {
  // ✅ Vegetables
  tomato: "tomato",
  "red pepper": "tomato",
  "vase": "tomato",
  capsicum: "capsicum",
  "bell pepper": "capsicum",
  onion: "onion",
  shallot: "onion",
  garlic: "garlic",
  ginger: "spices",
  potato: "potato",
  "sweet potato": "potato",
  peas: "peas",
  "green peas": "peas",
  spinach: "spinach",
  carrot: "mixed vegetables",
  cauliflower: "mixed vegetables",
  cabbage: "mixed vegetables",
  broccoli: "mixed vegetables",
  chili: "green chili",
  "green chili": "green chili",
  "green pepper": "green chili",

  // ✅ Grains & Pulses
  rice: "rice",
  pulao: "rice",
  biryani: "rice",
  flour: "flour",
  bread: "bread",
  loaf: "bread",
  lentil: "lentils",
  "red lentil": "lentils",
  beans: "rajma beans",
  "kidney beans": "rajma beans",
  chickpea: "chickpeas",
  "garbanzo": "chickpeas",
  rava: "rava",
  semolina: "rava",
  "flattened rice": "flattened rice",
  poha: "flattened rice",
  noodles: "noodles",
  pasta: "pasta",

  // ✅ Dairy
  milk: "milk",
  curd: "yogurt",
  yogurt: "yogurt",
  dahi: "yogurt",
  paneer: "paneer",
  cheese: "paneer",
  tofu: "paneer",
  cream: "cream",
  butter: "butter",
  ghee: "ghee",

  // ✅ Proteins
  chicken: "chicken",
  cock: "chicken",
  hen: "chicken",
  meat: "chicken",
  egg: "eggs",
  omelet: "eggs",
  fish: "fish",
  salmon: "fish",
  tuna: "fish",

  // ✅ Spices / Oils
  masala: "spices",
  curry: "spices",
  spice: "spices",
  ginger: "spices",
  chili: "spices",
  "red chili": "spices",
  "green chili": "green chili",
  oil: "olive oil",
  "olive oil": "olive oil",
  sauce: "soy sauce",
  "soy": "soy sauce",
  "soybean": "soy sauce",
  "coconut": "coconut milk",
  "coconut milk": "coconut milk",
};

export default forceMap;
